/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import ViewModels.ListarVM;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sebastián Lobos Díaz
 */
public class listaMiembros extends javax.swing.JFrame {

    /**
     * Creates new form ListaMiembros
     */
    private TableRowSorter sorter;

    public listaMiembros() {
        initComponents();

        try {
            String currentDirectory = System.getProperty("user.dir");
            String fontPath = currentDirectory + "/src/Font/BlackFuture.otf";
            String fontPath2 = currentDirectory + "/src/Font/Natural Precision.ttf";

            Font customFont = Font.createFont(Font.TRUETYPE_FONT, new File(fontPath));
            Font customFont2 = Font.createFont(Font.TRUETYPE_FONT, new File(fontPath2));

            customFont = customFont.deriveFont(80f);
            customFont2 = customFont2.deriveFont(24f);

            lblTituloListaMiembros.setFont(customFont);

            btnListar.setFont(customFont2);
            btnVolver.setFont(customFont2);
            btnFiltro.setFont(customFont2);
            
            cmbFiltroTaller.setFont(customFont2);
            cmbFiltroDias.setFont(customFont2);

        } catch (IOException | FontFormatException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        pnlTituloListaMiembros = new javax.swing.JPanel();
        lblTituloListaMiembros = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Miembros = Tabla_Miembros = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        cmbFiltroTaller = new javax.swing.JComboBox<>();
        btnFiltro = new javax.swing.JButton();
        cmbFiltroDias = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlBase.setBackground(new java.awt.Color(30, 30, 30));
        pnlBase.setForeground(new java.awt.Color(255, 255, 255));

        pnlTituloListaMiembros.setBackground(new java.awt.Color(61, 61, 61));

        lblTituloListaMiembros.setFont(new java.awt.Font("Segoe UI", 0, 69)); // NOI18N
        lblTituloListaMiembros.setForeground(new java.awt.Color(1, 176, 187));
        lblTituloListaMiembros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloListaMiembros.setText("LISTA DE MIEMBROS");

        javax.swing.GroupLayout pnlTituloListaMiembrosLayout = new javax.swing.GroupLayout(pnlTituloListaMiembros);
        pnlTituloListaMiembros.setLayout(pnlTituloListaMiembrosLayout);
        pnlTituloListaMiembrosLayout.setHorizontalGroup(
            pnlTituloListaMiembrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloListaMiembrosLayout.createSequentialGroup()
                .addComponent(lblTituloListaMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        pnlTituloListaMiembrosLayout.setVerticalGroup(
            pnlTituloListaMiembrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloListaMiembros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        pnlBotones.setBackground(new java.awt.Color(61, 61, 61));

        btnListar.setBackground(new java.awt.Color(1, 176, 187));
        btnListar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/list.png"))); // NOI18N
        btnListar.setText("LISTAR");
        btnListar.setBorderPainted(false);
        btnListar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnListar.setIconTextGap(10);
        btnListar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(1, 176, 187));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/flechaizq.png"))); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        Tabla_Miembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla_Miembros);

        cmbFiltroTaller.setBackground(new java.awt.Color(50, 55, 65));
        cmbFiltroTaller.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbFiltroTaller.setForeground(new java.awt.Color(255, 255, 255));
        cmbFiltroTaller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtro por taller", "Taller de Defensa Personal", "Taller de Kickboxing Fitness", "Taller de Kung-Fu", "Taller de Jiu-Jitsu", "Taller de Tai Chi" }));

        btnFiltro.setBackground(new java.awt.Color(1, 176, 187));
        btnFiltro.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/list.png"))); // NOI18N
        btnFiltro.setText("FILTRAR");
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });

        cmbFiltroDias.setBackground(new java.awt.Color(50, 55, 65));
        cmbFiltroDias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbFiltroDias.setForeground(new java.awt.Color(255, 255, 255));
        cmbFiltroDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtro por dia", "30 ", "90", "180" }));
        cmbFiltroDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFiltroDiasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloListaMiembros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1666, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(120, Short.MAX_VALUE))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbFiltroTaller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFiltroDias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(btnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))))
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addComponent(pnlTituloListaMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(cmbFiltroTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFiltroDias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ListarVM lista;
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        
        lista.SearchClientes(0, 0);

    }//GEN-LAST:event_btnListarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);

        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        inicio.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Object[] objects = {
            Tabla_Miembros
        };
        
        lista = new ListarVM(objects);
    }//GEN-LAST:event_formWindowActivated

    private void cmbFiltroDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltroDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFiltroDiasActionPerformed

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
        System.out.println(cmbFiltroTaller.getSelectedIndex() + " " + cmbFiltroDias.getSelectedIndex());
        lista.SearchClientes(cmbFiltroTaller.getSelectedIndex(), cmbFiltroDias.getSelectedIndex());
    }//GEN-LAST:event_btnFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaMiembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaMiembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaMiembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaMiembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaMiembros().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Miembros;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbFiltroDias;
    private javax.swing.JComboBox<String> cmbFiltroTaller;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloListaMiembros;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlTituloListaMiembros;
    // End of variables declaration//GEN-END:variables
}
